// client/src/App.tsx
import "./App.css";
import { useComponentValue, useQuerySync } from "@dojoengine/react";
import { Entity } from "@dojoengine/recs";
import { useEffect, useState } from "react";
import { getEntityIdFromKeys } from "@dojoengine/utils";
import { useDojo } from "./dojo/useDojo";

function App() {
    const {
        setup: {
            systemCalls: { move },
            clientComponents: { Position, Global, Pool },
            toriiClient,
            contractComponents,
        },
        account,
    } = useDojo();

    useQuerySync(toriiClient, contractComponents as any, []);

    let global_key = getEntityIdFromKeys([BigInt(0)]) as Entity;
    let pool_key = getEntityIdFromKeys([BigInt(40)]) as Entity;

    let global = useComponentValue(Global, global_key);
    let pool = useComponentValue(Pool, pool_key);


    console.log(global)
    console.log(pool)


    return (
        <>
            <button onClick={() => account?.create()}>
                {account?.isDeploying ? "deploying burner" : "create burner"}
            </button>
            

            <div className="card">
                <div>{`burners deployed: ${account.count}`}</div>
                <div>
                    select signer:{" "}
                    <select
                        value={account ? account.account.address : ""}
                        onChange={(e) => account.select(e.target.value)}
                    >
                        {account?.list().map((account, index) => {
                            return (
                                <option value={account.address} key={index}>
                                    {account.address}
                                </option>
                            );
                        })}
                    </select>
                </div>
                <div>
                    <button onClick={() => account.clear()}>
                        Clear burners
                    </button>
                </div>
            </div>

            <div className="card">
               
            </div>
        </>
    );
}

export default App;

// client/src/App.svelte
<script lang="ts">
    import type { Entity } from "@dojoengine/recs";
    import { componentValueStore } from "./componentValueStore";
    import { dojoStore, burnerManagerStore } from "./stores";
    import type { ComponentStore } from "./componentValueStore";

    let entityId: Entity;
    let address: string;
    let player: ComponentStore;
    

    $: ({ clientComponents, torii, burnerManager, client } = $dojoStore);

    $: if (torii) entityId = torii.poseidonHash([burnerManager.getActiveAccount()?.address!])

    $: if (dojoStore) player = componentValueStore(clientComponents.Player, entityId);

    $: if (burnerManagerStore) (burnerManager = $burnerManagerStore)

    $: account = burnerManager.account ? burnerManager.account : burnerManager.masterAccount;

    function handleBurnerChange(event: Event) {
        const target = event.target as HTMLSelectElement;
        address = target.value;
        console.log(address)
        burnerManager.select(address);
        console.log(burnerManager.getActiveAccount()?.address)
    }

</script>

<main>
    {#if $dojoStore}
        <p>Setup completed</p>
    {:else}
        <p>Setting up...</p>
    {/if}

    <button on:click={() => burnerManager?.create()}>
        {burnerManager?.isDeploying ? "deploying burner" : "create burner"}
    </button>

    <div class="card">
        <div>{`burners deployed: ${burnerManager.list().length}`}</div>
        <div>
            select signer:{" "}
            <select on:change={handleBurnerChange}>
                {#each burnerManager?.list() as account}
                        <option value={account.address}>
                            {account.address}
                        </option>
                {/each}
            </select>
        </div>
        <div>
            <button on:click={() => burnerManager.clear()}>
                Clear burners
            </button>
            <p>
                You will need to Authorise the contracts before you can
                use a burner. See readme.
            </p>
        </div>
    </div>

    <div class="card">
        <button on:click={() => client.gacha.mint({account})}>Spawn</button>
        
        <div>
            player has {$player?.pieces.length} pieces
        </div>


    </div>

</main>
